### ISSUE TITLE
Events Pipeline leads to a Broken Image

### ISSUE THREAD

**Issue by adamcoppard** [sedostheatre/sedos.co.uk#2420]
In 7f3abfb95e205da1026e9f23c98e1eaadc25f89c we published an Event for the Titanic auditions, which in the CMS had an image displayed in the left hand after selecting from the image picker. However, in the preview on the right hand side, and when published, this resulted in a broken image.

**Comment by olevett** [comment]
I can't see anything actually wrong here, in either the output (e.g. https://github.com/sedostheatre/sedos.co.uk/blob/08ade2525fbf93440968e649e3689fb483e03938/events/titanic-auditions.html) or the assets in that commit, so I'm going to chalk it up to CDN/caching/weirdness unless there are some other repro cases (it's not something anyone else has reported that I know of) and close this.
